name: OLED Build Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  TOOLCHAIN: "4.0.0.52"
  DFP: "ATmega_DFP.3.6.299"
  PROJECT_PATH: "./demo"
  OUTPUT_FOLDER: "output"

jobs:
  build-firmware-m16a-tty-software-twi:
    env:
      DEVICE: "atmega16a"
      FIRMWARE_NAME: "tty_sw_twi_m16a"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr;SSD130X_USE_SOFT_TWI"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target tty_twi_m16a -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m16a-tty-software-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m16a-tty-hardware-twi:
    env:
      DEVICE: "atmega16a"
      FIRMWARE_NAME: "tty_hw_twi_m16a"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target tty_twi_m16a -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m16a-tty-hardware-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m16a-frame-software-twi:
    env:
      DEVICE: "atmega16a"
      FIRMWARE_NAME: "frame_sw_twi_m16a"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr;SSD130X_USE_SOFT_TWI"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target frame_twi_m16a -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m16a-frame-software-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m16a-frame-hardware-twi:
    env:
      DEVICE: "atmega16a"
      FIRMWARE_NAME: "frame_hw_twi_m16a"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target frame_twi_m16a -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m16a-frame-hardware-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m4808-tty-software-twi:
    env:
      DEVICE: "atmega4808"
      FIRMWARE_NAME: "tty_sw_twi_m4808"
      PREPROCESSOR: "F_CPU=20000000UL;SSD130X_HAL_PLATFORM=avr0;SSD130X_USE_SOFT_TWI"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}

    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}

    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target tty_twi_m4808 -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m4808-tty-software-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m4808-tty-hardware-twi:
    env:
      DEVICE: "atmega4808"
      FIRMWARE_NAME: "tty_hw_twi_m4808"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr;TWI_PORTMUX=PORTMUX_TWI0_ALT2_gc"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target tty_twi_m4808 -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m4808-tty-hardware-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m4808-frame-software-twi:
    env:
      DEVICE: "atmega4808"
      FIRMWARE_NAME: "frame_sw_twi_m4808"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr;SSD130X_USE_SOFT_TWI"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target frame_twi_m4808 -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m4808-frame-software-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1

  build-firmware-m4808-frame-hardware-twi:
    env:
      DEVICE: "atmega4808"
      FIRMWARE_NAME: "frame_hw_twi_m4808"
      PREPROCESSOR: "F_CPU=12000000UL;SSD130X_HAL_PLATFORM=avr;TWI_PORTMUX=PORTMUX_TWI0_ALT2_gc"
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repository
      uses: actions/checkout@v7
    
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
        git submodule update --remote --recursive

    - name: Copy license
      run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}
          cp ./LICENSE.md ./${{ env.OUTPUT_FOLDER }}
    
    - name: Install necessary packages
      run: sudo apt-get install -y zip cmake

    - name: Switch to project directory
      run: cd ./${{ env.PROJECT_PATH }}
    
    - name: Install build tools
      run: |
          wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-${{ env.TOOLCHAIN }}-linux.any.x86_64.tar.gz
          tar -xf *.tar.gz
    
    - name: Install DFP package
      run: |
          wget https://packs.download.microchip.com/Microchip.${{ env.DFP }}.atpack
          unzip *.atpack -d ./DFP
    
    - name: Build firmware
      run: |
        cmake -S . -B build \
          -DCMAKE_TOOLCHAIN_FILE=cmake/platforms/avr/toolchain-avr-gcc.cmake \
          -DAVR_DEFINES:STRING="${{ env.PREPROCESSOR }}"

        cmake --build build/ --target frame_twi_m4808 -j

    - name: Copy firmware to output folder
      run: |
        mkdir -p ./${{ env.OUTPUT_FOLDER }}
        cp build/*.hex ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.hex
        cp build/*.map ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.map
        cp build/*.lss ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.lss
        cp build/*.eep ../${{ env.OUTPUT_FOLDER }}/${{ env.FIRMWARE_NAME }}.eep

    - name: Switch to base directory
      run: cd ..
    
    - name: Archive build artifacts
      run: |
        tar -czvf build.tar.gz ./${{ env.OUTPUT_FOLDER }}
        zip -r build.zip ./${{ env.OUTPUT_FOLDER }}

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v7
      with:
        name: firmware-m4808-frame-hardware-twi
        path: ./${{ env.OUTPUT_FOLDER }}
        retention-days: 1